# ArchE Browser Automation Configuration
# This file contains configuration settings for the ArchE browser automation system

# Browser Configuration
browser:
  headless: false  # Set to true for production
  viewport:
    width: 1920
    height: 1080
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  timeout: 30000  # 30 seconds
  retries: 3

# Security Configuration
security:
  session_timeout: 3600  # 1 hour in seconds
  max_retries: 3
  delay_range: [1, 3]  # Random delay between actions (seconds)
  human_like_typing: true
  encryption_key_derivation_iterations: 100000
  credential_expiry_days: 30

# Platform Configurations
platforms:
  fetlife:
    base_url: "https://fetlife.com"
    login_url: "https://fetlife.com/login"
    search_endpoints:
      - "/search"
      - "/groups"
      - "/events"
      - "/users"
    rate_limit: 10  # requests per minute
    selectors:
      username: 'input[name="nickname_or_email"]'
      password: 'input[name="password"]'
      submit: 'input[type="submit"]'
      search: 'input[name="q"]'
      results: '.search-result, .user-card, .group-card'
    
  skipthegames:
    base_url: "https://skipthegames.com"
    login_url: "https://skipthegames.com/login"
    search_endpoints:
      - "/posts"
      - "/search"
      - "/escorts"
    rate_limit: 15  # requests per minute
    selectors:
      search: 'input[type="search"]'
      results: '.posting, .listing, .result-item'
    
  twitter:
    base_url: "https://twitter.com"
    login_url: "https://twitter.com/login"
    search_endpoints:
      - "/search"
      - "/explore"
    rate_limit: 20
    selectors:
      username: 'input[name="text"]'
      password: 'input[name="password"]'
      submit: '[data-testid="LoginForm_Login_Button"]'
      search: '[data-testid="SearchBox_Search_Input"]'
      results: '[data-testid="tweet"]'

# Search Configuration
search:
  default_timeout: 10000  # 10 seconds
  max_results: 50
  result_types:
    - "users"
    - "groups"
    - "events"
    - "posts"
    - "general"
  
# Anti-Detection Configuration
anti_detection:
  randomize_user_agents: true
  simulate_mouse_movements: true
  random_scrolling: true
  typing_speed_variance: 0.05  # Standard deviation for typing speed
  click_delay_variance: 0.5    # Standard deviation for click delays
  
# CAPTCHA Solving Configuration
captcha:
  enabled: true
  services:
    - "2captcha"
    - "anticaptcha"
    - "capmonster"
  timeout: 120  # 2 minutes
  retry_attempts: 3
  
# Proxy Configuration (Optional)
proxy:
  enabled: false
  rotation: true
  providers:
    - "luminati"
    - "smartproxy"
    - "oxylabs"
  
# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "arche_automation.log"
  max_size: "10MB"
  backup_count: 5
  
# Data Storage Configuration
storage:
  credentials_file: "arche_credentials.json"
  sessions_file: "arche_sessions.json"
  results_file: "arche_search_results.json"
  backup_enabled: true
  encryption_enabled: true
  
# Rate Limiting Configuration
rate_limiting:
  enabled: true
  default_delay: 2  # seconds between requests
  burst_limit: 5    # max requests in burst
  window_size: 60   # seconds
  
# Error Handling Configuration
error_handling:
  max_consecutive_errors: 5
  error_cooldown: 300  # 5 minutes
  retry_exponential_backoff: true
  max_retry_delay: 60  # seconds
  
# Monitoring Configuration
monitoring:
  enabled: true
  metrics_collection: true
  performance_tracking: true
  alert_thresholds:
    error_rate: 0.1  # 10%
    response_time: 5000  # 5 seconds
    success_rate: 0.9  # 90%








