name: Nightly Snapshot

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run snapshot
        run: python arche_snapshot.py 